package com.Research;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author super
 */
public class BellCurveGUI extends javax.swing.JFrame {

    /**
     * Creates new form BellCurveGUI
     */
    public BellCurveGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minXBox = new javax.swing.JTextField();
        minYBox = new javax.swing.JTextField();
        maxXBox = new javax.swing.JTextField();
        maxYBox = new javax.swing.JTextField();
        minXLabel = new javax.swing.JLabel();
        minYLabel = new javax.swing.JLabel();
        maxXLabel = new javax.swing.JLabel();
        maxYLabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        standardDevCheckbox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        doneButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        minXBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minXBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minXBoxActionPerformed(evt);
            }
        });

        minYBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minYBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minYBoxActionPerformed(evt);
            }
        });

        maxXBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxXBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxXBoxActionPerformed(evt);
            }
        });

        maxYBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxYBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxYBoxActionPerformed(evt);
            }
        });

        minXLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minXLabel.setText("Minimum X-Axis Scale Value:");

        minYLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minYLabel.setText("Minimum Y-Axis Scale Value:");

        maxXLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maxXLabel.setText("Maximum X-Axis Scale Value:");

        maxYLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maxYLabel.setText("Maximum Y-Axis Scale Value:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(maxXLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(maxXBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(minXLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(minXBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(minYLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                                .addComponent(maxYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(maxYBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(minYBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addContainerGap(132, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 146, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(minXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(minXLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(maxXLabel)
                                                .addComponent(maxXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(minYLabel)
                                                .addComponent(minYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(maxYLabel)
                                                .addComponent(maxYBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        title.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Bell Curve");

        standardDevCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        standardDevCheckbox.setSelected(true);
        standardDevCheckbox.setText("Draw Standard Deviation Lines");
        standardDevCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardDevCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(standardDevCheckbox)
                                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(standardDevCheckbox)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doneButton))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(doneButton)
                                        .addComponent(cancelButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void minXBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if(DataProcessor.isInteger(minXBox.getText())){
            minX = DataProcessor.convertToInteger(minXBox.getText());

        } else {
            JOptionPane.showMessageDialog(null, "Error: Incorrect data type", "Error", JOptionPane.ERROR_MESSAGE);
            minXBox.setText("INT");
            minX = null;

        }
    }

    private void minYBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if(DataProcessor.isDouble(minYBox.getText())){
            minY = DataProcessor.convertToDouble(minYBox.getText());

        } else {
            JOptionPane.showMessageDialog(null, "Error: Incorrect data type", "Error", JOptionPane.ERROR_MESSAGE);
            minYBox.setText("DOUBLE");
            minY = null;

        }
    }

    private void maxXBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if(DataProcessor.isInteger(maxXBox.getText())){
            maxX = DataProcessor.convertToInteger(maxXBox.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Error: Incorrect data type", "Error", JOptionPane.ERROR_MESSAGE);
            maxXBox.setText("INT");
            maxX = null;
        }
    }

    private void maxYBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if(DataProcessor.isDouble(maxYBox.getText())){
            maxY = DataProcessor.convertToDouble(maxYBox.getText());

        } else {
            JOptionPane.showMessageDialog(null, "Error: Incorrect data type", "Error", JOptionPane.ERROR_MESSAGE);
            maxYBox.setText("DOUBLE");
            maxY = null;
        }
    }

    private void standardDevCheckboxActionPerformed(java.awt.event.ActionEvent evt) {
        drawSDLines = standardDevCheckbox.isSelected();
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        cancelled = true;
        this.dispose();
    }

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(minX == null || minY == null || maxX == null || maxY == null){
            JOptionPane.showMessageDialog(null, "Error: Please complete all fields", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            cancelled = false;
            this.dispose();
            Main.makeBellCurve();
        }
    }

    //Getters
    public int getMinX() {
        return minX;
    }

    public double getMinY() {
        return minY;
    }

    public int getMaxX() {
        return maxX;
    }

    public double getMaxY() {
        return maxY;
    }

    public boolean isCancelled() {
        return cancelled;
    }

    public boolean isDrawSDLines() {
        return drawSDLines;
    }

    //My variables
    private Integer minX;
    private Double minY;
    private Integer maxX;
    private Double maxY;
    private boolean cancelled = false;
    private boolean drawSDLines = true;

    // Variables declaration - do not modify
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField maxXBox;
    private javax.swing.JLabel maxXLabel;
    private javax.swing.JTextField maxYBox;
    private javax.swing.JLabel maxYLabel;
    private javax.swing.JTextField minXBox;
    private javax.swing.JLabel minXLabel;
    private javax.swing.JTextField minYBox;
    private javax.swing.JLabel minYLabel;
    private javax.swing.JCheckBox standardDevCheckbox;
    private javax.swing.JLabel title;
    // End of variables declaration
}

